### ISSUE TITLE
How to make constraints to slide animation

### ISSUE THREAD

**Issue by sonder-joker** [badoo/Decompose#114]
I wish to make a slide animation 
but how to constraints it

**Comment by sonder-joker** [comment]
The mp3 seem not work....
I make a custom column which specific width 160dp, but when I add slide animation it will over the column and to the far left of the screen.I wish it can disappear in the sidebar

**Comment by arkivanov** [comment]
Hi. It is not clear what is the problem without video, or some code. But maybe you can use `clip` Modifier on your custom column.

**Comment by sonder-joker** [comment]
https://user-images.githubusercontent.com/56215747/114644194-9f6e3b00-9d09-11eb-8c02-bc42a5ba3455.mp4

It exceeds that column, I hope to make it disappear in that column

**Comment by arkivanov** [comment]
I think Modifier.clip on the container should help. If not, could you provide a reproducer?

**Comment by sonder-joker** [comment]
I don't know how to do it...The code is here and I change to use crossfadescale()
https://github.com/sonder-joker/mirai-compose/blob/8c78c483eeff33d9d7308c26101e9bcdbca1ba3c/mirai-compose/src/main/kotlin/ui/feature/plugin/PluginsView.kt#L65

**Comment by sonder-joker** [comment]
Also I have some question about stack navigation.
Consider UI with video above.I have five selection text
![QQ图片20210421114523](https://user-images.githubusercontent.com/56215747/115493858-14f08300-a297-11eb-94ea-0cb461542ed0.png)
The robot column can be choose to login many account so I make such a navigation
```kotlin
sealed class Config : Parcelable {
        class BotR(val bot:Bot) : Config()
        object Setting : Config()
        object About : Config()
        object Log : Config()
        object Plugin : Config()
}
```
```kotlin
is Config.BotR -> {
    BotState(
        componentContext,
        bot = currentBot,
        index = _botIndex,
        onLoginSuccess = { index, bot ->
            miraiComposeRepository.setNullToBot(index, bot)
        }
    ).asComponent { BotStateUi(it) }
}
```
and the navigation in``` BotR ```component
```kotlin
sealed class BotStatus : Parcelable {
        object NoLogin : BotStatus()
        class SolvePicCaptcha(val imageBitmap: ImageBitmap, val onSuccess: (String?) -> Unit) :
            BotStatus()

        class SolveSliderCaptcha(val url: String, val result: (String?) -> Unit) : BotStatus()
        class SolveUnsafeDeviceLoginVerify(val url: String, val result: (String?) -> Unit) : BotStatus()
        object Online : BotStatus()
}
```
```kotlin
 is BotStatus.Online ->
        BotOnline(componentContext, bot!!).asComponent { BotOnlineUi(it) }
```
However something wrong happened.Every time I navigate to the ```BotR``` will loss all of message I make in the ```BotOnline```previous
And if I choose this way
```kotlin
sealed class Config : Parcelable {
        class BotR(val bot:Bot) : Config()
        object Setting : Config()
        object About : Config()
        object Log : Config()
        object Plugin : Config()
}
```
It will not update.I wish to know the best practice.

**Comment by arkivanov** [comment]
> I don't know how to do it...The code is here and I change to use crossfadescale()
> https://github.com/sonder-joker/mirai-compose/blob/8c78c483eeff33d9d7308c26101e9bcdbca1ba3c/mirai-compose/src/main/kotlin/ui/feature/plugin/PluginsView.kt#L65

I can't verify the issue, the Plugin section is empty. I think you should wrap `Children` call into e.g. `Box`:
```kotlin
@Composable
fun PluginsUi(plugins: Plugins) {
    Box(Modifier.clipToBounds()) {
        Children(plugins.state, animation = slide()) { child ->
            child.instance()
        }
    }
}
```.

**Comment by arkivanov** [comment]
> Also I have some question about stack navigation.
> Consider UI with video above.I have five selection text
> ![QQ图片20210421114523](https://user-images.githubusercontent.com/56215747/115493858-14f08300-a297-11eb-94ea-0cb461542ed0.png)
> The robot column can be choose to login many account so I make such a navigation
> 
> ```kotlin
> sealed class Config : Parcelable {
>         class BotR(val bot:Bot) : Config()
>         object Setting : Config()
>         object About : Config()
>         object Log : Config()
>         object Plugin : Config()
> }
> ```
> 
> ```kotlin
> is Config.BotR -> {
>     BotState(
>         componentContext,
>         bot = currentBot,
>         index = _botIndex,
>         onLoginSuccess = { index, bot ->
>             miraiComposeRepository.setNullToBot(index, bot)
>         }
>     ).asComponent { BotStateUi(it) }
> }
> ```
> 
> and the navigation in`BotR`component
> 
> ```kotlin
> sealed class BotStatus : Parcelable {
>         object NoLogin : BotStatus()
>         class SolvePicCaptcha(val imageBitmap: ImageBitmap, val onSuccess: (String?) -> Unit) :
>             BotStatus()
> 
>         class SolveSliderCaptcha(val url: String, val result: (String?) -> Unit) : BotStatus()
>         class SolveUnsafeDeviceLoginVerify(val url: String, val result: (String?) -> Unit) : BotStatus()
>         object Online : BotStatus()
> }
> ```
> 
> ```kotlin
>  is BotStatus.Online ->
>         BotOnline(componentContext, bot!!).asComponent { BotOnlineUi(it) }
> ```
> 
> However something wrong happened.Every time I navigate to the `BotR` will loss all of message I make in the `BotOnline`previous
> And if I choose this way
> 
> ```kotlin
> sealed class Config : Parcelable {
>         class BotR(val bot:Bot) : Config()
>         object Setting : Config()
>         object About : Config()
>         object Log : Config()
>         object Plugin : Config()
> }
> ```
> 
> It will not update.I wish to know the best practice.

It is not clear what are you doing and how your project works. It seems that that the `BotOnline` component is child of the `BotState` component. If so, then most likely `BotOnline` is recreated when you are navigating to `BotState`. Please provide a reproducer (or exact steps to reproduce the issue) so I could help.

**Comment by sonder-joker** [comment]
> It is not clear what are you doing and how your project works. It seems that that the `BotOnline` component is child of the `BotState` component. If so, then most likely `BotOnline` is recreated when you are navigating to `BotState`. Please provide a reproducer (or exact steps to reproduce the issue) so I could help.

Consider your example project. TodoMain with some TodoItem, I wish to load the data in TodoItem in background even if I leave the TodoItem Ui(such as in TodoMain).I don't want to recreate TodoItem,I just want to recreate TodoItemUi,like viewmodel. Sorry for my poor English, if you need more detailed explain, I will create a gist later
May a Hashmap in TodoMain could solve it, but I don't think it's a good action?

**Comment by arkivanov** [comment]
> > It is not clear what are you doing and how your project works. It seems that that the `BotOnline` component is child of the `BotState` component. If so, then most likely `BotOnline` is recreated when you are navigating to `BotState`. Please provide a reproducer (or exact steps to reproduce the issue) so I could help.
> 
> Consider your example project. TodoMain with some TodoItem, I wish to load the data in TodoItem in background even if I leave the TodoItem Ui(such as in TodoMain).I don't want to recreate TodoItem,I just want to recreate TodoItemUi,like viewmodel. Sorry for my poor English, if you need more detailed explain, I will create a gist later
> May a Hashmap in TodoMain could solve it, but I don't think it's a good action?

What should happen when the app is restarted?

**Comment by sonder-joker** [comment]
Within a few days after answering the issue, I rethinked the design. My previous thinking was problematic.
(In the following thinking, each Componentcontext corresponds to a @Composable Ui)  

What I am doing is the GUI of an open source robot project. My original idea was to start subscribing to a flow (including message events) after entering OnlineBot.
```
                   NavHost
                      |
                      |
                      |
 -------------------------------------------
 |          |         |         |          |
 |          |         |         |          |
 Plugin     OnlineBot Setting   About      Log
 ...
```  
For this reason, I split the project into a `Login` page and an `OnlineBot` page. When the Login page is finished logging in, I navigate to the OnlineBot  
Initially I hope to enter OnlineBot at this time to start and keey subscribing the bot message flow (the question in the above part), even if I leave OnlineBot, I will continue to subscribe the bot message flow. My mistake is to subscribe the message flow in the ComponentContext of `OnlineBot`, but this way I navigate to After OnlineBot will re-subscribe to flow. In fact, I should subscribe to data in `NavHost`'s ComponentContext. This example is very similar to the news bar of a news website. Should the clicked news be cached in memory? I'm not sure, but in my project, all robot data should stay in memory, so I can place it in NavHost and load it.  
Now I think the question may could close.  
Thanks you very much,Decompose's architecture is impressive!Decompose is an great open source project, and I look forward to it's development!

**Comment by arkivanov** [comment]
Please keep in mind that you can integrate Sub-Components into parents directly, without using the `Router`. So they are still separate children, but they live in the same scope as the parent. The Counter sample has this logic. For example the `Root` component has navigating parts and the permanent part. Take a look [here](https://github.com/arkivanov/Decompose/blob/efa62ba35b2f4a937d866b7818ecfcd66b96913c/sample/counter/shared/src/commonMain/kotlin/com/arkivanov/sample/counter/shared/root/CounterRootComponent.kt#L22). In this case your NavHost will not be responsible for anything except orchestrating its children.

**Comment by sonder-joker** [comment]
> Please keep in mind that you can integrate Sub-Components into parents directly, without using the `Router`. So they are still separate children, but they live in the same scope as the parent. The Counter sample has this logic. For example the `Root` component has navigating parts and the permanent part. Take a look [here](https://github.com/arkivanov/Decompose/blob/efa62ba35b2f4a937d866b7818ecfcd66b96913c/sample/counter/shared/src/commonMain/kotlin/com/arkivanov/sample/counter/shared/root/CounterRootComponent.kt#L22). In this case your NavHost will not be responsible for anything except orchestrating its children.

Thanks! I have miss this part. Todo project is a bit difficult to understand because of many libraries, and I only read Todo project. I will read the project!

**Comment by arkivanov** [comment]
The Todo sample don't have this, the Counter sample does.
