### ISSUE TITLE
Any plan for test?

### ISSUE THREAD

**Issue by sonder-joker** [badoo/Decompose#122]
I think current there is not a simle way to test a class implementation ComponentContext (for example, how to provide ComponentContext)

**Comment by arkivanov** [comment]
Could you please elaborate what is the issue and what you are trying to achieve?

**Comment by sonder-joker** [comment]
I have a simle class that  implementation 
```kotlin
class InitLogin(
    componentContext: ComponentContext,
    private val onClick: (account: Long, password: String) -> Unit,
) : ComponentContext by componentContext {
    private val scope = instanceKeeper.getOrCreate(::ComponentChildScope)

    private var _account by mutableStateOf(TextFieldValue())

    val account get() = _account

    private var _password by mutableStateOf(TextFieldValue())

    val password get() = _password

    private var _hasAccountError by mutableStateOf(false)

    val hasAccountError get() = _hasAccountError

    private var _hasPasswordError by mutableStateOf(false)

    val hasPasswordError get() = _hasPasswordError

    var errorTip by mutableStateOf("")

    private var _loading by mutableStateOf(false)

    val loading get() = _loading

    fun onAccountTextChange(textFieldValue: TextFieldValue) {
        if (textFieldValue.text.matches("^[0-9]{0,15}$".toRegex())) {
            _account = textFieldValue
            _hasAccountError = false
        } else {
            _hasAccountError = true
            scope.launch {
                delay(1000)
                _hasAccountError = false
            }
        }
    }

    fun onPasswordTextChange(textFieldValue: TextFieldValue) {
        _password = textFieldValue
    }

}
```
and also UI like that 
```kotlin
@Composable
fun InitLoginUi(initLogin: InitLogin) {
    Column(
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier.fillMaxSize()
    ) {
        AccountTextField(
            account = initLogin.account,
            onAccountTextChange = initLogin::onAccountTextChange,
            isError = initLogin.hasAccountError,
            errorLabel = initLogin.errorTip,
            onKeyEnter = initLogin::onLogin
        )
        PasswordTextField(
            password = initLogin.password,
            onPasswordTextChange = initLogin::onPasswordTextChange,
            isError = initLogin.hasPasswordError,
            errorLabel = initLogin.errorTip,
            onKeyEnter = initLogin::onLogin
        )
        LoginButton(
            onClick = initLogin::onLogin,
            isLoading = initLogin.loading
        )
    }
}
```
If I wish to test ui, I have to construct a InitLogin class, but to construct a class need a ComponentContext.
For now the only way is `rememberRootComponent`.Is there a better way?

**Comment by arkivanov** [comment]
Thanks for the explanation. You can extract an interface from your `InitLogin` class. I played with UI tests recently, you can find an example [here](https://github.com/arkivanov/android-dev-challenge-compose-1/blob/main/app/src/androidTest/java/com/example/androiddevchallenge/details/PuppyDetailsUiTest.kt).

**Comment by sonder-joker** [comment]
> Thanks for the explanation. You can extract an interface from your `InitLogin` class. I played with UI tests recently, you can find an example [here](https://github.com/arkivanov/android-dev-challenge-compose-1/blob/main/app/src/androidTest/java/com/example/androiddevchallenge/details/PuppyDetailsUiTest.kt).

Thanks! I have consider this way,but I can only test ui in this way.
Some times I just want to test the implementation class simple...the fake class also need time to write.I wish to a better way.

**Comment by arkivanov** [comment]
Then you probably need integration tests, not just UI. An example of logic integration tests can be found [here](https://github.com/JetBrains/compose-jb/blob/master/examples/todoapp/common/main/src/commonTest/kotlin/example/todo/common/main/integration/TodoMainTest.kt). You can convert this test to instrumented and add UI.

**Comment by arkivanov** [comment]
I recommend writing unit and component integration tests in JUnit (as they are fast and reliable), and just test dummy UI in instrumented tests.

**Comment by sonder-joker** [comment]
thanks!
