### ISSUE TITLE
Router.pop throwing Exception 

### ISSUE THREAD

**Issue by Shabinder** [badoo/Decompose#123]
When I call router.pop within a few milliseconds of pushing a child, An exception is thrown with the following Message: 
`"Configuration stack can not be empty"`

Am I doing something wrong, but if I call router.pop say after a delay of 200ms, it works as expected

**Comment by arkivanov** [comment]
Could you please provide a reproducer?

**Comment by Shabinder** [comment]
@arkivanov , Here it is: https://github.com/Shabinder/SpotiFlyer/tree/318c673cea9cd05652317c3f0c828bd0216014d2

Remove Following Delay to reproduce the Exception:

![image](https://user-images.githubusercontent.com/44765050/116449760-1feb7a80-a878-11eb-9787-61b35af3d3aa.png)

its in projectDir/common/compose/list/SpotiFlyerListUI.kt

**Comment by arkivanov** [comment]
Thanks! The project is big, what are steps to reproduce?

**Comment by arkivanov** [comment]
The error is pretty much descriptive, it is not allowed to pop the only child (the last one). Are you sure there are at least two children in the stack at the time when you call `pop`?

**Comment by Shabinder** [comment]
> The error is pretty much descriptive, it is not allowed to pop the only child (the last one). Are you sure there are at least two children in the stack at the time when you call `pop`?

I have 2 Screens 
1) Main(Default/Initial) -> 2) List Screen
 

after I push List Screen into router (while I was on Main) and as soon as I enter List Screen and call router.pop , it throws this error.

Am I making sense?

PS: I believe I call pop so early that I don't give time to router to initialize its stack? is this possible? but I only Call router.pop from Screen 2, if it's being shown, it means the router is initialized, isn't it?
Is there any delay/processing that happens between **Pushing an Element** and **New Router State Initialisation**, which can maybe cause this issue?

**Comment by Shabinder** [comment]
> Thanks! The project is big, what are steps to reproduce?


I forgot that this is using 2 deps from mavenLocal, I havent published them yet, so in order to build the project/**Android App**,
these repos need to be pushed to localMaven, that is, execute publishtoMavenLocal task for these repos:
 - https://github.com/Shabinder/youtube-api-dl
 - https://github.com/Shabinder/fuzzywuzzy

**Comment by arkivanov** [comment]
There are no any delays. It should be safe to `pop` as soon as `push` call returns.

**Comment by Shabinder** [comment]
> There are no any delays. It should be safe to `pop` as soon as `push` call returns.

I dont know then what could be the issue, However using delay is not a very big issue for me right now. As it gives few ms to show a loading anim too,for user satisfaction  🙃

**Comment by arkivanov** [comment]
@Shabinder  It is till not clear how to reproduce the crash. What exact steps should I perform in your project? What should I type into the edit field?

I removed the delay and just typed some random text - there is infinite loading indicator and nothing else. No crash.

**Comment by arkivanov** [comment]
Also the project did not compile:
`e: /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/desktop/src/jvmMain/kotlin/Main.kt: (68, 24): Object is not abstract and does not implement abstract member public abstract val setDownloadDirectoryAction: () -> Unit defined in com.shabinder.common.root.SpotiFlyerRoot.Dependencies`
I had to add empty callback there.

**Comment by Shabinder** [comment]
Aah you are testing Desktop version , I havent actually been developing desktop app , Try building Android App 

when you will enter random char in searchbar , an Exception will be dispatched as shown below: 
![image](https://user-images.githubusercontent.com/44765050/116464361-84630580-a889-11eb-8e75-85df796af0a6.png)
and this exception will cause router.pop as shown below
![image](https://user-images.githubusercontent.com/44765050/116464536-b7a59480-a889-11eb-8482-1d5bd2f2fb42.png)


If I use a delay, router.pop will work correctly and a Toast will appear as shown below
![image](https://user-images.githubusercontent.com/44765050/116464673-e28fe880-a889-11eb-8e9e-3968e09c4cda.png)

But if you disable the delay and bring model.errorOccured?.let{/******/} out of lauched Effect you will get the Exception as shown below,
![image](https://user-images.githubusercontent.com/44765050/116465172-7feb1c80-a88a-11eb-9dfd-05609a6be397.png)


PS: we have been encountering an infinite loading bar if you just simply comment delay out and let it be in Launched Effect, bcuz using UNIT as a key make it only render once and It doesnt get exec again upon state change, to make this work bring the code out of lauched effect or use error as the key, I just moved it out to reproduce.

PS: its 1:32 am in India, So I am gonna take off now, will visit this back in the morning if you have made any progress. and I am sorry you had to mess around to get it to build, my project is still in a very early stage, So as I encountered the issue, I just wanted to inform you about the same. Thanks for all your help and patience. Good Night.

**Comment by arkivanov** [comment]
The Android app does not compiple either:
```
Execution failed for task ':android:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/nullnull/debug/google-services.json
  /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/debug/nullnull/google-services.json
  /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/nullnull/google-services.json
  /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/debug/google-services.json
  /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/nullnullDebug/google-services.json
  /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/google-services.json
```

**Comment by Shabinder** [comment]
> The Android app does not compiple either:
> 
> ```
> Execution failed for task ':android:processDebugGoogleServices'.
> > File google-services.json is missing. The Google Services Plugin cannot function without it. 
>    Searched Location: 
>   /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/nullnull/debug/google-services.json
>   /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/debug/nullnull/google-services.json
>   /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/nullnull/google-services.json
>   /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/debug/google-services.json
>   /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/src/nullnullDebug/google-services.json
>   /home/aivanov/dev/workspace/SpotiFlyer-318c673cea9cd05652317c3f0c828bd0216014d2/android/google-services.json
> ```

Ohhh nooo let me fix this for you and you can just use my latest pull to reproduce.

**Comment by arkivanov** [comment]
> But if you disable the delay and bring model.errorOccured?.let{/******/} out of lauched Effect

Making side effects directly from `@Composable` functions is incorrect, the function may be executed multiple times in a row, and so you will `pop` multiple times as well. You should produce side effects from things like `LaunchedEffect`, `DisposableEffect`, click actions, etc.

**Comment by Shabinder** [comment]
@arkivanov  just pull the latest changes in the New_DM_Android Branch , and build , it should crash as soon as you type any random char

**Comment by Shabinder** [comment]
> > But if you disable the delay and bring model.errorOccured?.let{/******/} out of lauched Effect
> 
> Making side effects directly from `@Composable` functions is incorrect, the function may be executed multiple times in a row, and so you will `pop` multiple times as well. You should produce side effects from things like `LaunchedEffect`, `DisposableEffect`, click actions, etc.

Yeah I just noticed that if I use it in LaunchedEffect with error as a key , this works as expected

**Comment by Shabinder** [comment]
Rookie Mistake I guess, Sorry for all the inconvenience. Closing it now

**Comment by arkivanov** [comment]
Glad to help, feel free to ask any questions!
