### ISSUE TITLE
Add a web app for the Master-Detail sample

### ISSUE THREAD

**Issue by arkivanov** [badoo/Decompose#141]
The sample is [here](https://github.com/arkivanov/Decompose/tree/master/sample/master-detail), would be good to add a web app for it, perhaps using React. Another web app can be found in the [Counter sample](https://github.com/arkivanov/Decompose/tree/master/sample/counter/app-js), just for reference.

**Comment by maxtox3** [comment]
@arkivanov, I want to try

**Comment by arkivanov** [comment]
Thank you, feel free to ask any questions!

**Comment by arkivanov** [comment]
Big thanks for the contribution!
Closed via #159.
