### ISSUE TITLE
NoSuchMethodError: No interface method startReplaceableGroup with Compose 1.0.0-beta07

### ISSUE THREAD

**Issue by soniccat** [badoo/Decompose#150]
Got this exception after trying to update Compose to 1.0.0-beta07

```   
 java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/com.aglushkov.wordteacher.androidApp-4keQzDtu0r5s9Ue6Ncp8XQ==/base.apk)
        at com.arkivanov.decompose.extensions.compose.jetpack.RootComponentBuilderKt.rememberRootComponent(Unknown Source:15)
        at com.aglushkov.wordteacher.androidApp.MainActivity$setupComposeLayout$1$1$1.invoke(MainActivity.kt:56)
        at com.aglushkov.wordteacher.androidApp.MainActivity$setupComposeLayout$1$1$1.invoke(MainActivity.kt:54)
```

Got the error here: https://github.com/soniccat/WordTeacher/tree/decomppose_no_such_method_error

I hope this slack thread might help: https://kotlinlang.slack.com/archives/CJLTWPH7S/p1621432061225200?thread_ts=1621431472.224500&cid=CJLTWPH7S

**Comment by arkivanov** [comment]
The binary compatibility in Jetpack Compose was broken in `beta07` and so Decompose has to be recompiled with the new version.

![IMG_20210522_201205_049](https://user-images.githubusercontent.com/26204457/119238412-2947ca00-bb3a-11eb-9cad-79f46404d0a5.jpg)

But `beta07` has a [bug affecting UI state preservation](https://issuetracker.google.com/issues/188567661), it is not restored when navigating back. So perhaps better to wait for the next release, unless there are strong reasons to use `beta07`.

**Comment by SteynSieveo** [comment]
This also affects Jetbrains Compose for Desktop. I'm upgraded to version 0.4.0-build209 and I see the same behaviour here too.
It seems like the bug affecting UI state that you refer to has been fixed already, but I don't know if that fix has made its way to Jetbrains' Compose already or not.

**Comment by arkivanov** [comment]
That makes sense, thanks! I will check again tonight.

**Comment by arkivanov** [comment]
The bug is indeed fixed in Compose for Desktop `0.4.0-build209`, but it requires Kotlin `1.5.0`, however the latest version of Jetpack Compose `beta07` requires Kotlin `1.4.32`. It is better to wait for a version of Jetpack Compose with Kotlin `1.5.0`, I think it should be the next version. I would like to avoid manual publication without `extensions-compose-jetpack` module, unless there are hard blockers for anybody.

**Comment by arkivanov** [comment]
Update: Jetpack Compose `beta08` will have both Kotlin `1.5.0` and the bug fix. It will be released June 2nd.

**Comment by arkivanov** [comment]
Please drop a message here if someone is hard blocked by the crash, I will try to do a manual publication for you in this case.

**Comment by SteynSieveo** [comment]
Thanks for the update @arkivanov. 
This is not hard blocking me, just keeping me from updating to the new compose and kotlin 1.5.0.

2nd of June is not that far away, so it think it is fine. :)

**Comment by sonder-joker** [comment]
wait for the release

**Comment by arkivanov** [comment]
Version `0.2.5` is released, please allow some time for the Maven Central sync process.

**Comment by soniccat** [comment]
Thanks, but it seems in 08 they have broken LazyColumn: https://issuetracker.google.com/issues/189170789 ... will wait next release)
