### ISSUE TITLE
Add watchOS support

### ISSUE THREAD

**Issue by plusmobileapps** [badoo/Decompose#155]
* Apple watchOS on ARM64 (Apple Watch Series 4 and newer)
* ARM32 (earlier models) platforms
* desktop simulators

**Comment by arkivanov** [comment]
May I ask how urgent is it?

**Comment by plusmobileapps** [comment]
Not urgent at all! Just putting this in the backlog when you get a chance. Perhaps even something I could help out with?

**Comment by arkivanov** [comment]
@plusmobileapps This should be like a 10 min task, unless I am missing something. The setup should be similar to [tvos](https://github.com/arkivanov/Decompose/blob/32775ea1353eb2f2534cacb3f8c05cbaf3859ec3/build.gradle#L222), I will appreciate your help. I'm planning a release next week, so as a last resort I will do it myself closer to the release.

**Comment by plusmobileapps** [comment]
I can try to give it a shot, although I think the [MviKotlin watchOS support](https://github.com/arkivanov/MVIKotlin/issues/229) would be helpful to actually test the integration with watchOS. Guessing something similar as well for that library.

**Comment by arkivanov** [comment]
MVIKotlin is a bit trickier, as it has some advanced configuration (which I actually want to refactor at some point). So probably I will do it myself. Decompose does not depend on MVIKotlin, so can be updated separately. Tests will show if everything alright.

**Comment by arkivanov** [comment]
Closed via #156. Thanks @plusmobileapps for your contribution!
