### ISSUE TITLE
[Survey] Parcelize for Darwin (Apple) targets

### ISSUE THREAD

**Issue by arkivanov** [badoo/Decompose#157]
I would like to understand, do we need Parcelize support for Darwin (Apple) targets? I built an experimental [kotlin-parcelize-darwin](https://github.com/arkivanov/kotlin-parcelize-darwin) compiler plugin, which is similar to `kotlin-parcelize`. We could enable it in a separate branch and start publishing the experimental version of `decompose` module, with a version suffix. More info in my [article](https://medium.com/bumble-tech/writing-kotlin-parcelize-compiler-plugin-for-ios-678d81eed27e?source=friends_link&sk=45d45bf2af472f4237f58fb6519367a8).

Please put 👍 if you think it is useful, or 👎 if you believe the state preservation is not important on iOS, watchOS, macOS, etc. Please feel free to leave a comment or ask a question.

**Comment by moffpage** [comment]
It was actually strange to see you implementing this because I believe you've said parcelize plugin doesn't make sense on Apple platforms since if I recall the platform does it automatically, but I may confuse this with another state preservation (view or something else). But nonetheless Apple still has NSConding protocols, so they serve some value. I might investigate into it a bit and later provide more feedback. I very much appreciate your work and contribution into the community

**Comment by arkivanov** [comment]
> It was actually strange to see you implementing this because I believe you've said parcelize plugin doesn't make sense on Apple platforms since if I recall the platform does it automatically, but I may confuse this with another state preservation (view or something else). But nonetheless Apple still has NSConding protocols, so they serve some value. I might investigate into it a bit and later provide more feedback. I very much appreciate your work and contribution into the community

Thanks! I don't remember such words from my side. On iOS, the process death due to memory pressure is much more rare than on Android. And so it might be acceptable to loose the state (both data and navigation stack) in such rare cases. But it is still the case, and it might be a requirement for an app to support it.

**Comment by moffpage** [comment]
It probably refers to the fact that Android and iOS handle configuration changes differently, I'm trying to find the exact text so I could quote you, but I'm having a little trouble doing it, so maybe if you give me some time, I can provide it to you :)

**Comment by moffpage** [comment]
Probably this, but maybe somewhere else too: https://proandroiddev.com/decompose-experiments-with-kotlin-multiplatform-lifecycle-aware-components-and-navigation-a04ef3c7f6a3
<img width="707" alt="image" src="https://user-images.githubusercontent.com/33549573/119967359-17e53e80-bfce-11eb-9727-946ed48b92de.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/33549573/119967505-39dec100-bfce-11eb-9e87-6a65bff47786.png">

**Comment by arkivanov** [comment]
Thanks, but it does not sound like "parcelize plugin doesn't make sense on Apple platforms". Am I missing something? Anyway, I think it does make sense, but not so important as on Android. :-)

**Comment by moffpage** [comment]
Probably doesn't, although I remember a little different approach to saying this, which as I said I couldn't easily find. If I find it, I'll definitely recall if you don't mind, but yeah. If you feel it makes sense, maybe it's a game-changer! Even a little :D. I'm interested in your colleagues opinion on this survey. What do they think about it?

**Comment by arkivanov** [comment]
`Parcelize` was extracted to [Essenty](https://github.com/arkivanov/Essenty) library. Closing for now.
