### ISSUE TITLE
How does Decompose handle routing with dynamic feature components?

### ISSUE THREAD

**Issue by moffpage** [badoo/Decompose#158]
Hello! I've watched this video earlier today: https://www.youtube.com/watch?v=iURWvHxTM3k&list=LL&index=4 and it got me curios, what does Decompose offer for its clients for dynamic feature loading?

**Comment by arkivanov** [comment]
I remember @rustamsmax used Decompose and Dynamic Features, could you please share your experience?

**Comment by rsktash** [comment]
Dynamic module is platform specific feature.
When I implemented it I created `feature availability checker` class and` feature renderer `class using reflection.
I passed the `checker` class to decompose component which use it to decide when routing screens. If featureA available it navigates to HomeA else HomeMain.
For the ui I passed the `renderer` class via ambients. When decompose component navigates to HomeA this class is used to render featureA ui.
If it's multi platform project you can create fake checkers for desktop app which will return always true.

Here is my project module tree where I used dynamic features
![image](https://user-images.githubusercontent.com/36570577/120298936-f2b14280-c2e3-11eb-9e6b-7b4d6f3724dc.png)

**Comment by arkivanov** [comment]
I will think about adding an example for dynamic features.

**Comment by moffpage** [comment]
Oh God, that'd be amazing!
