### ISSUE TITLE
Parcelize fails in Kotlin 1.4.21-release-studio4.2.1

### ISSUE THREAD

**Issue by tieskedh** [badoo/Decompose#16]
- the methods don't get their functions `describeContents` and `toParcel` functions
- Parcelize fails, because it has no constructor

**Comment by arkivanov** [comment]
Please make sure your are using the new `kotlin-parcelize` plugin. Check out this doc: https://kotlinlang.org/docs/reference/whatsnew1420.html#new-plugin-for-parcelable-implementation-generator

If you still have problems, could you please provide a reproducer?

**Comment by tieskedh** [comment]
Thanks!
Before I went bak to 1.4.20, I saw that it indeed solved the issue.
(I went back as my main function could not be found anymore, as it is not supported yet)
