### ISSUE TITLE
Add a watchOS sample app to the counter

### ISSUE THREAD

**Issue by plusmobileapps** [badoo/Decompose#166]
With the recent addition of [watchOS support in Decompose](https://github.com/arkivanov/Decompose/issues/155), it could be helpful to have a sample with the target in the [counter app](https://github.com/arkivanov/Decompose/tree/master/sample/counter).  I do see that MVIKotlin is still pending support for [watchOS support](https://github.com/arkivanov/MVIKotlin/issues/229), so I'm guessing to integrate the shared code in the repository would need to wait for that issue to be resolved? Or are there other solutions out there instead of MVIKotlin as an architecture for the model?

**Comment by arkivanov** [comment]
The Counter sample does not use MVIKotlin, but it does use Reaktive. The latter is also pending `watchosX64` target which I will add this Friday. Other watchOS targets are already supported, so it should be possible to start working on it.

Are you going to contribute this sample?

**Comment by plusmobileapps** [comment]
Good to hear, I'd like to help contribute for this sample as I have been wanting to learn more watchOS development. I could probably help out with the master detail iOS sample as well. Just wasn't sure if it could be done yet, I must have been thinking of the Todo sample that uses MVIKotlin.

**Comment by arkivanov** [comment]
Perhaps the master-detail sample is not really suitable for watches? You can start with the Counter sample already, just avoid `watchosX64` target for now.

**Comment by plusmobileapps** [comment]
Sorry should have mentioned just implementing the master detail sample issue as an iOS app, watch would be a little overkill😂 I'll try to work on the watch sample over the next couple days 👍

**Comment by arkivanov** [comment]
Ah yes! There is an open [issue](https://github.com/arkivanov/Decompose/issues/142) for adding iOS app for the master-detail sample. Please let me know which you would like to peak first, I will assign it to you. Thanks!

**Comment by plusmobileapps** [comment]
I will say I have been tinkering around with this off and on the last week and might need a little help as I am mainly an Android developer who has been trying to learn iOS. I was trying to look for a sample of watchOS which the [KMM documentation](https://kotlinlang.org/docs/mobile/samples.html#peopleinspace) mentioned [People in Space](https://github.com/joreilly/PeopleInSpace) targeted watchOS. But even that sample currently has an [issue of running watchOS on the emulator](https://github.com/joreilly/PeopleInSpace/issues/12).  @arkivanov do you happen to know if the shared code needs to be packed in a framework or do we need to use a separate plugin like [multiplatform-swiftpackage](https://github.com/ge-org/multiplatform-swiftpackage) similar to people in space for accessing the shared code on the watchOS app?

**Comment by arkivanov** [comment]
@plusmobileapps From the first sight the `multiplatform-swiftpackage` plugin is used to integrate the shared module as XCFramework via Swift Package Manager. It is not clear yet, but I think it should also work via so called "direct" integration, using the `packForXcode` Gradle task and a build phase script in Xcode. This is already being used in all samples. I think we should try this approach first with a dummy Xcode project for watchOS.

**Comment by arkivanov** [comment]
Closed via #190. Thanks for your contribution @plusmobileapps!
