### ISSUE TITLE
Describe routing options in the docs

### ISSUE THREAD

**Issue by arkivanov** [badoo/Decompose#179]
Docs page: https://arkivanov.github.io/Decompose/router/overview/

We should describe the `Navigator.navigate {}` function and all extension functions. Also describe the `Router` and the `Navigator` interfaces hierarchy.

**Comment by plusmobileapps** [comment]
Is there any examples using the `Navigator` API? I could probably help out with this

**Comment by arkivanov** [comment]
@plusmobileapps I would welcome a contribution here, thank you. The [Router](https://github.com/arkivanov/Decompose/blob/master/decompose/src/commonMain/kotlin/com/arkivanov/decompose/Router.kt) interface extends the [Navigator](https://github.com/arkivanov/Decompose/blob/master/decompose/src/commonMain/kotlin/com/arkivanov/decompose/Navigator.kt) interface, just for better interface segregation. So `Navigator` is used every time the `Router.navigate(...)` method is used.

We should also describe all extension functions located [here](https://github.com/arkivanov/Decompose/blob/master/decompose/src/commonMain/kotlin/com/arkivanov/decompose/NavigatorExt.kt).

**Comment by arkivanov** [comment]
Closed via #219. Thanks @plusmobileapps for the contribution!
