### ISSUE TITLE
Add `Navigator.navigateSingleTop` extension function

### ISSUE THREAD

**Issue by arkivanov** [badoo/Decompose#180]
See the [discussion](https://github.com/arkivanov/Decompose/discussions/178#discussioncomment-1005820) where it came from.

**Comment by arkivanov** [comment]
The name `navigateSingleTop` is misleading in this context, as it has different [semantics](https://developer.android.com/guide/components/activities/tasks-and-back-stack#ManifestForTasks) in Android. We should find a better name. This function should work in the following way:

- If there is already a component in the stack with configuration of type `T`, then that component should be moved to top of the stack.
- Otherwise a new component should be created and pushed to the stack.

Some possible names: `reorderToFront`, `makeOnTop`, `activate`, `activateOrPush`, `bringToFrontOrPush`

**Comment by aartikov** [comment]
@arkivanov 
`stack.filterNot { it::class == configuration::class } + configuration`

Maybe it would be better to compare values rather than classes?
Otherwise, we can't use enums for bottom navigation items.

**Comment by arkivanov** [comment]
@aartikov as per my comment above, this function is to ensure there is only one type of component in the stack, and to bring it to front. I suggest to use sealed classes instead of enums, or just use `navigate(...)` directly.
