### ISSUE TITLE
Navigator.bringToFront() not available in 0.3.1

### ISSUE THREAD

**Issue by plusmobileapps** [badoo/Decompose#231]
The new navigator extension function `bringToFront()` from #208 does not seem to be available in the latest version 0.3.1. Is there going to be a new version of Decomposed published soon with that available?

**Comment by arkivanov** [comment]
I wanted to accumulate more features into the release, but I can release an update today if it will be useful for you.

**Comment by arkivanov** [comment]
I think I can't do a quick release at the moment. There were API changes since 0.3.1 and I will need to prepare  0.4.0 release. It will take some time.

Can you copy the implementation of `bringToFront()` to your project for now?

**Comment by plusmobileapps** [comment]
No rush for now, I ended up copying over that function to my project in the meantime. Will keep an eye out for the next release, thank you!

**Comment by arkivanov** [comment]
Version 0.4.0 is out with this function
