### ISSUE TITLE
Runtime crash on Children

### ISSUE THREAD

**Issue by steelahhh** [badoo/Decompose#25]
I've recently updated to the latest version, and getting a crash when using new `Children` function: 
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/arkivanov/decompose/extensions/compose/jetpack/RouterStateComposableKt$Children$1;
        at com.arkivanov.decompose.extensions.compose.jetpack.RouterStateComposableKt.Children(RouterStateComposable.kt:27)
        at dev.steelahhh.decocrashtester.MainActivity$onCreate$1$1$1.invoke(MainActivity.kt:72)
        at dev.steelahhh.decocrashtester.MainActivity$onCreate$1$1$1.invoke(Unknown Source:10)
```

I'm using `extensions-compose-jetpack` in a plain Android module but can repro with a new empty compose project, adding decompose dependencies and using [this setup](https://github.com/arkivanov/Decompose#routing-example)

**Comment by arkivanov** [comment]
Thanks for the report. Would you be able to attach a reproducer project? Just a zip archive would be enough. Or a GitHub repository.

**Comment by steelahhh** [comment]
Sure! [Here's the repro](https://github.com/steelahhh/Decompose-Crash-Repro)

**Comment by arkivanov** [comment]
Thanks! The link looks broken, it gives 404. Could you please check?

**Comment by arkivanov** [comment]
Seems like the crash happens if the library is published from my MacOS machine. If published from another Ubuntu machine - it is fine. Will need some time to investigate. As a workariund, you can publish Decompose locally with a custom version.

**Comment by steelahhh** [comment]
I've tried that now, and getting the same issue (Mac OS as well). So I'm going to resort to `includeBuild` for now

**Comment by arkivanov** [comment]
@steelahhh Looks like I found a workaround fix for this crash: #28 . You mentioned that you reproduced the crash when published manually to a local repository. Would you mind to also check from that branch?

**Comment by steelahhh** [comment]
Yep, checked on that branch - doesn't crash now 👍

**Comment by arkivanov** [comment]
Version `0.1.5` is published, should be fixed now.
