### ISSUE TITLE
Unresolved imports in commonMain when adding the Bintray dependency

### ISSUE THREAD

**Issue by arkivanov** [badoo/Decompose#3]
For some reason all imports are unresolved when Decompose is added to a Multiplatform module as Bintray dependency.

**Comment by jimKarsh** [comment]
Created a blank android project and added decompose as a dependency; it shows up in the module configuration but not the gradle dependencies.

**Comment by arkivanov** [comment]
Maybe this is because of the MPP workaround, which is applied to `decompose` module as well. I will try to publish `decompose` without any hacks, and move Compose stuff to a separate android library module.

**Comment by arkivanov** [comment]
Alright, applying the following change fixes the publication:
![image](https://user-images.githubusercontent.com/26204457/95027213-bc58f000-068e-11eb-8aa1-459d5b8f05cb.png)

This adds the important comments to `pom` files:
![image](https://user-images.githubusercontent.com/26204457/95027229-d98dbe80-068e-11eb-9df2-56e1a2eab2a2.png)

This makes imports resolved. But it does not compile in a project that does not use Compose (and so the new compiler backend):
![image](https://user-images.githubusercontent.com/26204457/95027255-05a93f80-068f-11eb-81e6-bedb98348abd.png)

Will try to move Compose stuff to a separate module. Stay tuned!

**Comment by arkivanov** [comment]
@jimKarsh I have published version 0.0.8, this issue should be fixed now. There are now two modules:
- `decompose` - the main multiplatform module with all functionality (multiplatform)
- `extensions-compose` - all extensions and utils for Jetpack Compose (Android only)

Updated the [Setup section](https://github.com/arkivanov/Decompose#setup) of the Readme.

**Comment by steelahhh** [comment]
Checked with a blank project – all imports are resolved, library shows up in external libraries

**Comment by arkivanov** [comment]
Looks like this issue can be closed now. Feel free to reopen, if there are any issues.
