### ISSUE TITLE
Unit tests and testing library

### ISSUE THREAD

**Issue by gumil** [badoo/Decompose#6]
Are there any plans or ideas of having a testing library to create something like an integration test of navigations in common code?

With regards to tests, are writing tests for the project planned anytime soon? I'll be glad to contribute in writing them.

**Comment by arkivanov** [comment]
Absolutely, unit tests are very important. Since Decompose API is now more stable, I will start testing it soon. Once some first tests are there I will appreciate contributions.

Regarding testing client code. Some tests will be available in the community within a few days. Please stay tuned. After that I will appreciate contributions in adding similar to Decompose samples. Also for navigation, I will add some tests to samples soon.

Let's keep this issue open.

**Comment by arkivanov** [comment]
So as promised, examples of unit and integration tests can found [here](https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp/common/main/src/commonTest/kotlin/example/todo/common/main). Examples of navigation testing are coming soon.

**Comment by arkivanov** [comment]
Just pushed navigation [tests](https://github.com/arkivanov/Decompose/tree/master/sample/todo/root/src/commonTest/kotlin/com/arkivanov/todo/root/integration) for sample Todo `root` module.

**Comment by arkivanov** [comment]
@gumil It would be nice if you could add tests for [MergedLifecycle](https://github.com/arkivanov/Decompose/blob/master/decompose/src/commonMain/kotlin/com/arkivanov/decompose/lifecycle/MergedLifecycle.kt). It accepts two `Lifecycles` and also implements `Lifecycle`. The state of the resulting `Lifecycle` (this) should always be minimum of the two.
I recently added tets for `Router`, sou you can check the code style [here](https://github.com/arkivanov/Decompose/tree/master/decompose/src/commonTest/kotlin/com/arkivanov/decompose/router).
Please note that you can't use mocking, so only stubs/fakes do work. For this particular case I believe you can use `LifecycleRegistry` to control input lifecycles.
If you don't want to contribute anymore, please do let me know, this is totally fine.

**Comment by gumil** [comment]
@arkivanov I won't be able to contribute for now.

**Comment by arkivanov** [comment]
Navigation test samples can be found [here](https://github.com/JetBrains/compose-jb/blob/master/examples/todoapp/common/root/src/commonTest/kotlin/example/todo/common/root/integration/TodoRootTest.kt).
