### ISSUE TITLE
compiled by an unstable version of the Kotlin compiler 

### ISSUE THREAD

**Issue by Shabinder** [badoo/Decompose#61]
error: Class 'com.arkivanov.decompose.extensions.compose.jetbrains.RouterStateComposableKt' is compiled by an unstable version of the Kotlin compiler and cannot be loaded by this compiler

**Comment by arkivanov** [comment]
Hello. Decompose uses Kotlin 1.4.20-2. Please use this version as of now.

**Comment by Shabinder** [comment]
> Hello. Decompose uses Kotlin 1.4.20-2. Please use this version as of now.

Thanks for quick reply

**Comment by arkivanov** [comment]
I'm waiting for Jetpack Compose to be updated to Kotlin 1.4.30. If you are using Desktop Compose, please stick to version `0.3.0-build146` for now.

**Comment by Shabinder** [comment]
after upgrading to 0.3.0-build146 and kotlin to 1.4.20-2 in my KMP project , Android gives error at setContent
![image](https://user-images.githubusercontent.com/44765050/107184284-4848a300-6a06-11eb-8f38-b791c330ec95.png)

**Comment by arkivanov** [comment]
Build 0.3.0-build146 should work fine with Kotlin 1.4.20-1. The error you are getting is bug in a newer version of Compose: https://github.com/JetBrains/compose-jb/issues/354

**Comment by Shabinder** [comment]
yup got fixed after cleaning and rebuilding after downgrading to 146
