### ISSUE TITLE
@Parcelize does not have a constructor error

### ISSUE THREAD

**Issue by Shabinder** [badoo/Decompose#62]
![image](https://user-images.githubusercontent.com/44765050/107159090-042cb280-69b4-11eb-8908-232cf9718dcd.png)

**Comment by arkivanov** [comment]
Please make sure you enabled kotlin-parcelize plugin, example: https://github.com/JetBrains/compose-jb/blob/c8b0ee23d0c18e130d223d2e8934bf5b25a67878/examples/todoapp/common/root/build.gradle.kts#L6

**Comment by Shabinder** [comment]
Thanks , I missed that.
