### ISSUE TITLE
Decompose API in iOS framework

### ISSUE THREAD

**Issue by gumil** [badoo/Decompose#7]
Decompose API that are not used in the shared module is not exported to the iOS framework. For example when `MutableValue` is not exposed through a public interface it won't be exported in the framework therefore you can't use it in iOS code.

Maybe I am missing a configuration? I'm not sure. I'm thinking on top of my head that maybe a cocoapods is needed to directly access its APIs?

**Comment by arkivanov** [comment]
Looks like this is a common behaviour of KMM, I bumped into this multiple time. My workaround always was to dummy-use the API in Kotlin that I need only in iOS. I will ask this in Kotlin Slack.

**Comment by arkivanov** [comment]
Do you explicitly export Decompose to the iOS framework?

**Comment by gumil** [comment]
I've tried it but it doesn't export. I guess it only exports local modules.

**Comment by arkivanov** [comment]
Ok, I will check. Thanks!

**Comment by arkivanov** [comment]
So I found a way to export all transitive dependencies:

![image](https://user-images.githubusercontent.com/26204457/98400247-9cd13080-205b-11eb-8ba6-d97ff715bc0d.png)

If you add `transitiveExport=true` flag it will export everything. But names will be not `DecomposeXxx` but just `Xxx`, which is even better.

**Comment by arkivanov** [comment]
Closing this for now. Feel free to reopen if there are any questions.

**Comment by gumil** [comment]
I had just a chance to try this approach. Koltin files with top level functions and a class won't import the top level functions. Only the class.

**Comment by arkivanov** [comment]
@gumil Top level functions are normally exported in a class named "FileNameKt". E.g. you have some top-level functions in a file named "Foo.kt". Then there should be a class exported, named "FooKt". All functions should be there. Could you please check?

**Comment by gumil** [comment]
It works now! thanks for the help. An additional information for anyone who'll ever see this issue is that the transitive dependency should be an API dependency

**Comment by arkivanov** [comment]
Yes, totally forgot about `api` qualifier. This actually not related to Decompose, but rather to Kotlin Multiplatform itself.😊 Glad it works now!
