### ISSUE TITLE
Adding Decompose into the Jetbrains KMM/Compose template

### ISSUE THREAD

**Issue by Wavesonics** [badoo/Decompose#76]
I started a project with the default template crated by IDEA for a KMM Compose project:
![image](https://user-images.githubusercontent.com/406473/108610816-80989b80-738d-11eb-903c-5e27a7fe414b.png)

Now I'm trying to add Decompse in, and it is having some issues.

I added the dependency to `common/build.gradle.kts` as such:
```kotlin
    ...
    sourceSets {
        val commonMain by getting {
            dependencies {
                api(compose.runtime)
                api(compose.foundation)
                api(compose.material)
                api(compose.ui)

                implementation("com.arkivanov.decompose:decompose:0.1.8")
                implementation("com.arkivanov.decompose:extensions-compose-jetbrains:0.1.8")
            }
        }
...
```

However in source files inside `commonMain` the IDE doesn't know about the classes. I can add them via manual import, but still, that seems like a problem, has anyone else encountered this?

**Comment by arkivanov** [comment]
Hi! Could you please provide a reproducer project, it would be really helpful.

**Comment by Wavesonics** [comment]
[notional.zip](https://github.com/arkivanov/Decompose/files/6016855/notional.zip)

I've tried IDEA Ultimate as well as Android Studio.

When you open it, go to `AppRoot.kt` under `commonMain` and try to `alt+enter` to auto-import the class, it will import an unrelated class from the JDK `import com.sun.jndi.toolkit.ctx.ComponentContext` presumably because it doesn't see the Decompose class of the same name.

**Comment by arkivanov** [comment]
Thanks! Looks like I understand what is the issue. For some reason IDE automatically imports a default package, which in this particular case is `com.sun.jndi.toolkit.ctx.ComponentContext`. Normally it should suggest a popup menu with options. But you can ignore this suggestion (don't press `Alt+Enter` or whatever hotkey you are using), and press `Ctrl+Space` (import hotkey on Linux, not sure about macOs), this shows popup with proper variants. This looks like an IDE bug which you can raise to [IDEA YouTrack](https://youtrack.jetbrains.com/issues/IDEA).

![Peek 2021-02-20 23-48](https://user-images.githubusercontent.com/26204457/108611434-68993a00-73d6-11eb-99a0-c06bb7e0595b.gif)

**Comment by arkivanov** [comment]
I used Android Studio 4.2 Beta 4, openjdk 14.0.2

**Comment by Wavesonics** [comment]
Ah that does it, thanks!
