### ISSUE TITLE
Failed to resolve dependency

### ISSUE THREAD

**Issue by StefanOltmann** [badoo/Decompose#82]
Hello,

maybe this has to do with the upcoming deprecation of JCenter.

I want to take a look at this framework in action by checking out https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp .

Unfortunately Gradle can't resolve the dependency:
`Failed to resolve: com.arkivanov.decompose:decompose:0.1.9`

Will this library eventually be available in Maven Central?

Kind regards,

Stefan

**Comment by arkivanov** [comment]
Hi, Decompose is currently published in JCenter. And JCenter is configured in the example TodoApp. The error you are seeing is likely [KTIJ-1113](https://youtrack.jetbrains.com/issue/KTIJ-1113). The project should compile fine.

Regarding publishing to Maven Central, indeed I will do it soon.

**Comment by StefanOltmann** [comment]
Hi,

thank you.

Yes, it's a bug in the current IDEA version and fixed in current early access.

Kind regards,

Stefan
