### ISSUE TITLE
Can we expect JS platform support for todo app too?

### ISSUE THREAD

**Issue by Shabinder** [badoo/Decompose#83]
I know there is js support for counter app , but to me TODO app's code and structure seems more lucid and I built desktop and android app learning from todo code , I was hoping if you have any plans to build a jsReact UI for todo app too?

**Comment by arkivanov** [comment]
Hi! I can do it for sure, but it all depends on JetBrains. Could you please transfer this request to https://github.com/JetBrains/compose-jb?

**Comment by Shabinder** [comment]
@arkivanov  compose-jb is kinda foccused repo for compose , aint it?
why not have a copy of todo app sample in Decompos's repo as we have counter already?

**Comment by arkivanov** [comment]
The TodoApp was in the Decompose repo originally, and was moved to compose-jb to avoid code duplication. The idea of the js UI implementation would be the same as in the Counter sample.

**Comment by Shabinder** [comment]
@arkivanov yeah i am new to WEB DEV, like I was trying to build the website like using Root Component with Main and Edit screen in to do using the root component's router.
But in WEB Dev i figure its diferrent?
I need a react-router for hanging screens and MVI concepts like store reducer-executor wont apply...i guess? 

So I am exploring some WEB Apps to grasp the idea.

I would love your input .... can we have a website just as we have Android's Compose using 1 root Component (which we use in android's Main Activity) and it itself handles all Intents and the router in it handles child changes.
Can we build a Web App using the same **root component** with React UI instead of Compose ? if yes , is there any sample/example using this approach.


for example sake lets say How will you build TODO in web? with Root and main/edit screens using the root component you have in TODO App.

**Comment by arkivanov** [comment]
This is exactly how it should work, just like in the sample Counter app. The navigation can be managed by Decompose.

**Comment by Shabinder** [comment]
Okay, I will study sampleCounter app in more details and will ask for help if needed here.

**Comment by arkivanov** [comment]
Feel free to ask any questions! I will keep this issue open for a while.

**Comment by Shabinder** [comment]
Hey , Got it working! ,Thanks.
