### ISSUE TITLE
Tutorial section in docs

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [badoo/Decompose#85]
- [x] Transitions
- [x] Deeplinks
      - Internal and external links
- [x] Multiple routers based on responsive design
      - Mobile screen size: Navigating from the master screen to the detail screen.
	  - Larger screen size: master and detail screens are visible at the same time, selecting one item in the master screen changes the content of the detail screen.
      - Sample: Gmail app in mobile vs tablet (But thinking that this should be possible to do resizing a desktop 
      screen, without losing the selected item, scroll position, etc).

**Comment by arkivanov** [comment]
@JavierSegoviaCordoba Are there any specific cases you have in mind?

**Comment by JavierSegoviaCordoba** [comment]
@arkivanov I changed it to checkboxes so if they are implemented they can be marked as done. If I think on more tutorials, I will add them there.

If someone wants to add something to the list, ping me and I will add :)

**Comment by arkivanov** [comment]
@JavierSegoviaCordoba Could you please elaborate what is "Multiple routers based on responsive design"?

**Comment by Shabinder** [comment]
> @JavierSegoviaCordoba Could you please elaborate what is "Multiple routers based on responsive design"?

I think that he meant like in web using  **2 column layout** with seperate router for each and using same code with different navigation in Android like using only one column per screen.

**Comment by JavierSegoviaCordoba** [comment]
Updated

**Comment by arkivanov** [comment]
Thanks for inputs! Let's also keep in mind that Decompose is a multiplatform library, and Compose is not the only companion.

**Comment by JavierSegoviaCordoba** [comment]
Yeah, my bad thinking on compose indeed, but I didn't want to repeat screen

**Comment by arkivanov** [comment]
Closed by the PRs above.
